### ISSUE TITLE
Selecting Shared Folder- wants a file?

### ISSUE THREAD

**Issue by dillera** [digarok/gsplus-legacy-archive#122]
First time user, really nice app. Thanks for your work on this totally free app.

Trying to setup a shared folder for GSPLUS- i navigate to a folder on OSX but the UI wants a file. I'm wondering exactly what type of file? I'm assuming you'd pick a folder and that would be shared as a PRODOS disk with the IIGS?

https://i.imgur.com/bJXjHRz.png

Also wondering what key combo does a reset - CTRL-OA-ESC just takes me to the DA page- I can't see how you reset the emulation like you would a real IIGS.

Also looking for some basic how-to docs and I don't see them here or on webpage. Am I missing something obvious?

Finally: Feature Request- I see you have integrated w/ Ethernet. Does the Emulation support SmartPort? If so is there any desire to integrate with our Virtual FujiNet? We have this working for the Atari Emulation and it works great. I can provide more info if this is anything you can see on your road map. Enabling FujiNet would open up a ton of possibilities for the emulation.

**Comment by dillera** [comment]
ok I did find:


`$ /Applications/GSplus.app/Contents/MacOS/gsplus -help`


also nice pod cast at: https://retrogameclub.net/skate-or-die-donkey-kong-country?tdest_id=1802600 I'm all for a IIGS emulation that mimics vagrant.

**Comment by dillera** [comment]
Just realized this project is abandoned!

**Comment by pacpir** [comment]
It is a shame if the project is abandoned.  I also very much love this app.

Sincerely,

Dr. Perry B. Sheidayi
