### ISSUE TITLE
Use intended colors instead of striping technique

### ISSUE THREAD

**Issue by RichAyotte** [digarok/gsplus-legacy-archive#15]
Vertical stripes are visible when running the emulator on a modern display.

![stripes](https://cloud.githubusercontent.com/assets/294987/23810296/fd9b40f8-059e-11e7-8b32-621cf6461527.png)

I understand this technique was used to simulate more colours on a CRT because of hardware limitations. 

Would it be possible for the emulator to show the intended colors instead of using this striping technique?

Here's a related discussion: https://groups.google.com/forum/#!msg/comp.sys.apple2/gKY7cFB55GQ/T7S48V-WMbEJ

**Comment by digarok** [comment]
Thanks for the suggestion.

One of the original goals of the project was to move to a standard rendering system (using SDL2) across all builds.  The idea was that it would simplify things, but also allow for an eventual addition of additional rendering effects, like possibly CRT emulation.

So in fact, the rendering of vertical stripes is accurate, but CRT displays were kind of blurring them out whereas a modern display is pixel perfect, allowing us to see them in all their ugly glory.

As pointed out in that last post by the great M.Mahon, there are different strategies, all with their own strengths and weaknesses.  A general blur would be easy, but probably unsatisfying for text and mouse pointer, etc.  A selective blur would be harder, but I think his ideas were on the right path.  And there are generalized routines for other emulators that may be easy enough to implement for a decent renderer, including some that are pixel shaders (moving that calculation to the GPU). 

I'll leave this open for now, but it requires further research, playing, and testing before I think I/we can commit to the best path forward.  I'd like to get it right on the first pass as much as possible.

Thanks again.

**Comment by digarok** [comment]
Now there are some enhancements that may help.  Fullscreen and resizeable modes automatically add some filtering.  There's also support for high dpi displays that might make it look better on those displays. 

Closing for now.  It can be re-evaluated if we ever move to more correct/advanced rendering such as CRT effects.
