### ISSUE TITLE
Corrupted display in Silent Service

### ISSUE THREAD

**Issue by n1ywb** [digarok/gsplus-legacy-archive#21]
Screen shots here

https://imgur.com/a/WCebd

It's playable, but it's ugly.

using gsplus experimental 84234e19a8abecabb4929856fb1f36160e70cfa9

**Comment by digarok** [comment]
Just curious, have you had a chance to check this disk image on another emulator or a real IIgs to see if the corruption shows on any other systems?

**Comment by digarok** [comment]
I do see the same menu corruption on latest versions of gsplus using the Silent Service image on Azimov.  I'll have to try to check via real hardware or other emulators, but I really think it might just be that this is a bad disk image.

**Comment by digarok** [comment]
Unable to prove that the disk isn't bad.  Closing.
