### ISSUE TITLE
Add fullscreen to CLI/config

### ISSUE THREAD

**Issue by digarok** [digarok/gsplus-legacy-archive#24]
It seems like you can only launch in windowed mode and hit F11 to fullscreen after it starts.

There are a lot of cases where it would be nice to be able to launch it and explicitly tell the emulator whether you want it to start in full-screen or windowed mode.

(Note: Scanline simulator is also a potential candidate for this.)

**Comment by ghost** [comment]
This would be awesome for seamless integration with things like launchbox / bigbox

**Comment by digarok** [comment]
Resolved in https://github.com/digarok/gsplus/pull/26
You can now add `-fullscreen` to launch in fullscreen
You can now add `-scanline 30` (0-100) to launch with the scanline simulator

This will be reflected in new builds.  The Windows version is still behind on SDL2 support so it may not make it into the next Windows build.
