### ISSUE TITLE
Mouse tracking in full screen not correct (4K display)

### ISSUE THREAD

**Issue by tschak909** [digarok/gsplus-legacy-archive#29]
Using GSPlus on Windows 10, with a 4K display (3840x2160), in full screen mode works, however, mouse movement does not track the display, properly.

Also, in lieu of this, can we get a window that can be resized arbitrarily? :)

-Thom

**Comment by digarok** [comment]
I've made some updates to the SDL2 version of the mouse code that tracks better, but I still think it can be improved. 

Also, the SDL2 versions support some nice new features like:  `-resizeable` to allow the window to be arbitrarily resized and `-borderless` to make a "chromeless" window.  There's also an `-x` and `-y` option to set the window position on launch.  You might try the `-highdpi` flag to see if that makes it look any better (to you) on your 4K display, though I don't think that is related to the mouse issues you saw. 

There's lots more, official release of 0.14 coming soon, but I highly suggest you try out one of the SDL builds available here: https://s3.amazonaws.com/gsplus-artifacts/index.html
