### ISSUE TITLE
FreeType not found when launching on OSX

### ISSUE THREAD

**Issue by digarok** [digarok/gsplus-legacy-archive#3]
Similar dynamic linking issues to Issue #2 ...

```
./gsplus
dyld: Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Referenced from: /Users/dbrock/Google Drive/appleiigs/rwiii/./gsplus
  Reason: image not found
Trace/BPT trap: 5
```

Can resolve, if brew is installed, using `brew install freetype`.

**Comment by rspeed** [comment]
It *appears* that both #2 and #3 have been fixed at some point. Running the most recent release (0.12s) on a machine without either library installed doesn't print any error messages. Additionally, this appears to be correct:

```console
$ otool -L /Applications/GSplus.app/Contents/MacOS/gsplus | grep -i freetype
@executable_path/../libs/libfreetype.6.dylib (compatibility version 19.0.0, current version 19.6.0)
```

**Comment by digarok** [comment]
This is resolved when using the Mac App Bundles now available at apple2.gs/plus 

As this is the recommended way to distribute Mac software, we should be ok to close this now.
