### ISSUE TITLE
ORCA/C PRIZM repainting issues

### ISSUE THREAD

**Issue by tschak909** [digarok/gsplus-legacy-archive#30]
After a few days of using ORCA/C inside GSPlus for development, I have now come across an odd repainting issue that only affects PRIZM, but makes the whole environment unusable:

https://www.youtube.com/watch?v=ZdgiWtSPL1w&feature=youtu.be

WTF?

I have reinstalled GSPlus
reinstalled System 6.0.1 and ORCA
zapped the PRAM
etc..etc..etc..

But this problem persists and does not change.

WTF????

-Thom

**Comment by mgcaret** [comment]
Do you have the GrafSpeed NDA installed, by chance?  It has this effect on Prizm.

**Comment by ksherlock** [comment]
I think we decided on facebook it was due to Easy Access (and is PRIZM's fault).

**Comment by mgcaret** [comment]
Ahh, I missed that.  I do know that GrafSpeed causes a similar problem in PRIZM, it drove me batty for a while.

**Comment by digarok** [comment]
Thanks for the information.  I'm going to consider this resolved and close.
