### ISSUE TITLE
Exiting Hangs on Ubuntu 18.04

### ISSUE THREAD

**Issue by sduensin** [digarok/gsplus-legacy-archive#33]
Closing the GSplus window on my Ubuntu box does not kill the gsplus process.  I have to kill -9 it.

**Comment by digarok** [comment]
Can you try a recent build and see if this is still the case? 
https://s3.amazonaws.com/gsplus-artifacts/index.html

I have fixed some of the SDL2 shutdown process which may have been causing this.  I'll try it myself too, but not sure I was ever able to reproduce it.  

Closing for now, but feel free to reopen if it's still happening.
