### ISSUE TITLE
Not an issue at all, just a mention of the great work being done.

### ISSUE THREAD

**Issue by GregWildman** [digarok/gsplus-legacy-archive#44]
Hi @digarok 

I was testing your current master branch (0.14rc) and was pleasantly surprised. I live in a terminal so I was tickled when I saw the ascii logo and structured formatting. I also like the icons for disk drive access.

Thanks

![gsplus-0 14rc](https://user-images.githubusercontent.com/4526433/44619503-d9078480-a887-11e8-8c51-e76082e3ad5e.png)

**Comment by digarok** [comment]
Awesome and thank you.  I will say that I've fixed some interesting bugs in the SDL2 driver in the last few days, so now it really runs at 60FPS.  I highly recommend picking up the latest from source, or from the latest builds page here:  https://s3.amazonaws.com/gsplus-artifacts/index.html

We hope to have more news soon.
