### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by GregWildman** [digarok/gsplus-legacy-archive#53]
Hello,

I see version 0.14 has been released on the website. Can you create a release/tag her as well ?

Thanks.

**Comment by digarok** [comment]
Wow, thank you so much for suggesting this.  Today I learned how to create tags and releases, how to delete tags and releases when you mess up (that part was less fun), and how to backdate tags to the commit date.  

This helps me fill a gap in-between the website and the development on github, and it will help others find releases more easily.  

Thank you very much.
https://github.com/digarok/gsplus/releases/tag/v0.14

P.S. - Active work on new release is underway! (And it will definitely be released/tagged here as well.)
