### ISSUE TITLE
Wrong aspect ratio?

### ISSUE THREAD

**Issue by puttesnutte** [digarok/gsplus-legacy-archive#60]
Shouldn't the aspect ratio of the picture be 4:3 (which it isn't if you don't run fullscreen in a 4:3 resolution without -fulldesk)?
I guess the IIgs doesn't have square pixels. But I have never used a real IIgs so I may be wrong.

**Comment by digarok** [comment]
You are correct that the Apple IIgs (and predecessors) did not have square pixels.  So everyone in emulator-land has to make the choice of integral aspect ratios or fractional aspect ratios.  The latter tend to look really bad so everyone goes with integral scaling factors.  However you can use command line flags to set the exact size of the window and also apply filtered scaling to improve the look of non-integral scaling factors.

Internally in GSplus, the screen is always rendered at a 2x scale factor.

In the future, we'll probably be using more high DPI displays with high level approximations of CRTs and their artifacts.  For now it's just a choice in emulation on which part of the emulation you want to break.
